method: bayes
metric:
  goal: maximize
  name: accuracy
parameters:
  temperature: 
    min: 0
    max: 2
  top_k: 
    min: 1
    max: 100
  top_p: 
    min: 0.01
    max: 1
  num_predict: 
    min: 8
    max: 512
